### ISSUE TITLE
fca4ynab creating adjustment transactions every time I sync

### ISSUE THREAD

**Issue by wizonesolutions** [borsboom/foreign-currency-accounts-for-ynab#23]
I have my fca4ynab set up to sync every 2 mins. It's pretty frequent, but it's still below the YNAB API limits, and it makes my life a bit easier.

One thing I've noticed is that, for some reason, it is now creating an adjustment transaction every time it syncs. I think this is recent, and I don't _think_ it happened when I installed the latest release.

Ah! I checked my transaction list, and it began on 29 Feb 2020. I guess we have a Y2K20 error happening :)

Other notes:

- if there are no transactions (other than Starting Balance) in the on-budget difference account, nothing happens
- credit difference accounts are not affected
- tracking difference accounts are not affected

It'd be fantastic if the fix could detect and delete the hundreds of duplicate transactions that have been created (or include manual fix instructions). There are 720 per day since 29 Feb 2020 (1440 minutes per day / every 2 minutes per hour), so the difference accounts load pretty slowly in YNAB. I feel like they will eventually contact me and ask why I have thousands of transactions.

**Comment by borsboom** [comment]
Ouch!  What are the amounts of the transactions?  Can you provide of the output with debug logging enabled (e.g. run `RUST_LOG=fca4ynab=debug fca4ynab --yes`).  In normal operation, fca4ynab should exit immediately if there were no new transactions (except the first run after midnight when it gets a new exchange rate and creates adjustment transactions).

**Comment by wizonesolutions** [comment]
Sure, will do. Can I email that to you or something since it's actual
numbers?

**Comment by wizonesolutions** [comment]
Oh, and except for the first transaction each day, they are typically 0.00
and 0.01 (inflows or outflows).

**Comment by borsboom** [comment]
Sure, please email to emanuel@borsboom.io.

My guess at this point is that a sub-cent transaction somehow ended up in one of your accounts that that's causing an "oscillation" that fca4ynab keeps trying to compensate for.

**Comment by borsboom** [comment]
Oh and please run a few times consecutively and send me all the logs, that way I hopefully can see the "oscillation" happening.

**Comment by borsboom** [comment]
Another thing you can try is go to your budget settings and change the number format have three decimal digits.  The third decimal digit of all your accounts _should_ be `0`, but an older version of fcay4ynab would create sub-cent transactions, which turned out to cause problems because some parts of the YNAB API round to the budget number format and other parts don't.  Other tools using the API may potentially also do that (I wish the API would just reject such transactions as invalid rather than silently accepting them and then behaving weird later).

It may be that changing this setting stops fca4ynab from creating these adjustments all the time.  Another thing you can try is adding a manual adjustment to get the third digit back to 0, and then see if that stops the problem even after changing back to a two decimal digit number format.

**Comment by wizonesolutions** [comment]
It's as you say; the adjustment accounts that are acting up have an erroneous third digit. This started on 29 Feb for both, which seems like a big coincidence to not be related at all. I'm going to send you logs, and then I will manually adjust the difference accounts to get the third digit back to 0 and keep an eye on it.

...OK, I grabbed the logs, but now it's not happening. That's probably because I'm at 3 digits...will switch back to 2 and grab some more logs...no, still nothing.

Guess I will just make manual adjustments and keep an eye on it. I keep looking at my crontab, and I'm definitely using the same arguments as I did on the command line...

Anyway, made the adjustments, and...no, this doesn't seem to be working.

Version, just for sanity:

```
fca4ynab 0.1.10
```

I think that's the latest.

OK, so I tried to get logs, but it only happens once now. It un-fixes my fixes, and then it just...leaves the third digit as non-zero. This must be a slightly different issue.

Ah, realized that maybe I needed to switch back to two digits before running it again...so trying after that...hmm, now it's only changing the other NOK credit and tracking accounts. I wonder if switching the number of digits _triggered_ something there. Checking again with three digits...no, those two accounts are still fine. I don't know why it did no-op adjustment transactions, but it's in the logs I will send you.

Re-enabling my cronjob, and I'll keep an eye on things.

**Comment by borsboom** [comment]
It's a bit hard to tell exactly what was going on from the logs, since you'd already started making changes to your settings at that point.

It seems to take a very specific set of circumstances to trigger this sort of problem, where the API has some kind of weirdness in the way it rounds account balances when there are sub-cent transactions (and you have a two-decimal-digit number format set) that causes fca4ynab to keep trying to compensate.   I never encountered the particular problem you had, but rather then problem reported in #8, which I believe is very related.

The only way I can think of to completely prevent oscillations is to skip creating adjustment transactions that are one cent (or equivalent depending on budget's decimal digits), which would mean the different account balances could be off by a cent up or down.  Maybe worth doing.

However, in theory, for users who started using the tool after #8 was fixed, this should never happen since it will never create sub-cent transactions anymore.  You get the early adopter bonus of extra weird bugs!

I can create a tool to help delete all those extra transactions.  What platform are you running fca4ynab on?

**Comment by wizonesolutions** [comment]
Thanks! Makes sense. I'm on macOS, currently.

**Comment by borsboom** [comment]
I've opened PR #25 that I believe should prevent this from ever happening again.

**Comment by borsboom** [comment]
> I can create a tool to help delete all those extra transactions. What platform are you running fca4ynab on?

Bad news: I can't create a tool to do this, because [the API doesn't provide a way to delete transactions](https://support.youneedabudget.com/t/36an21?r=63acbn).

**Comment by wizonesolutions** [comment]
Yeah, saw that. No problem

**Comment by borsboom** [comment]
Released in [v0.1.11](https://github.com/borsboom/foreign-currency-accounts-for-ynab/releases/tag/release/0.1.11).
