### ISSUE TITLE
Starting Balance special-cased?

### ISSUE THREAD

**Issue by wizonesolutions** [borsboom/foreign-currency-accounts-for-ynab#7]
Today I imported a CSV with transactions into one of my EUR accounts. The transactions after the Starting Balance date (11 Nov) worked fine, but the one from 8 Nov which I hadn't entered in my old budget either before switching is not getting picked up by the tool. I'm not sure how to make it get picked up.

It seems like you're probably caching the Starting Balance date in the data, and changing it to an earlier date doesn't get picked up. Is there a workaround?

**Comment by borsboom** [comment]
What date did you start using fca4ynab (or did you specify as the `--start-date` the first time you ran it)?  It will ignore any transactions with dates before then.

I'm not 100% certain this is the best behaviour, but it's what I chose for the sake of clarity -- it makes a clear delineation of "before fca4ynab" vs after.  An alternative would be for the tool to only use this start date on its first run (to avoid having to download your entire ledger), but all subsequent runs would process any added or updated transactions regardless of their date.

**Comment by wizonesolutions** [comment]
I think that processing updates in the accounts it manages (and maybe with a special switch, similar to how YNAB requires checking a box when importing) would be useful. In my case, all the managed accounts are newer anyway and don't have pre-fca4ynab activity.

**Comment by borsboom** [comment]
I've opened PR #10 that changes the behaviour so it processes all new and updated transactions regardless of date (so the start date is only used on the very first run).  If there's demand, I can add a flag to enable the old behaviour.

**Comment by borsboom** [comment]
If you'd like to test this without building from source, you can grab a binary by clicking on **Artifacts** on the top-right of https://dev.azure.com/borsboom/foreign-currency-accounts-for-ynab/_build/results?buildId=170.

**Comment by wizonesolutions** [comment]
Nice, will try to try that later.

**Comment by borsboom** [comment]
Released in [v0.1.6](https://github.com/borsboom/foreign-currency-accounts-for-ynab/releases/tag/release/0.1.6).

**Comment by wizonesolutions** [comment]
Works great, thanks!

**Comment by borsboom** [comment]
I'm not so happy with the change I made here, since it violates the principal of least surprise.  In particular, I made a bunch of changes to old transactions in foreign accounts, that existed before I started using this tool, and that then triggered this tool to create difference transactions for them when that's not what I wanted it to do.

It would be nice if there were an easy way to distinguish between *new* transactions vs. *updated* ones, but the YNAB API doesn't seem to provide an easy way to do that.  If we could, then we could ignore modified transactions from before the start date, but still process new transactions.

Instead, here's my proposal: the default start date shouldn't be the current day, but rather one month prior to the current day.  This way "late" imported transactions such as described in this issue's description will be caught.  In addition, it should be possible to change the start date after the first run, so that you can adjust it if you wish.

A further improvement could be to have different start dates per account rather than a single start date for the entire budget.  However, implementing this would end up requiring individual API calls for each account rather than the efficient single API call to get the latest transactions for all accounts at once.  Due to the API call limits, I'd prefer not to do that, since with the current setup it's possible to run this tool every five minutes without any risk of exhausting the limit.

**Comment by borsboom** [comment]
I've opened a PR #16 to default the start date to 30 days ago.

**Comment by borsboom** [comment]
Released in [v0.1.8](https://github.com/borsboom/foreign-currency-accounts-for-ynab/releases/tag/release/0.1.8).
